<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="Applications\Controls\ctrlApplicationBasicInfo.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Applications\Local Driving License\ctrlDrivingLicenseApplicationInfo.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Licenses\International Licenses\Controls\ctrlDriverInternationalLicenseInfo.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Licenses\Local Licenses\Controls\ctrlDriverLicenseInfoWithFilter.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Licenses\Controls\ctrlDriverLicenses.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="People\Controls\ctrlPersonCard.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="People\Controls\ctrlPersonCardWithFilter.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="User\ctrlUserCard.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Licenses\Local Licenses\Controls\ctrlDriverLicenseInfo.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Tests\Controls\crlScheduleTest.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Tests\Controls\ctrlSecheduledTest.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\DVLD_Buisness\DVLD_Buisness.csproj" />
    <ProjectReference Include="..\DVLD_DataAccess\DVLD_DataAccess.csproj" />
    <ProjectReference Include="..\DVLD_DTO\DVLD_DTO.csproj" />
    <ProjectReference Include="..\DVLD_Helper\DVLD_Helper.csproj" />
  </ItemGroup>
</Project>